on:
  push:
    branches:
      - main

name: install dataone

jobs:

  redland:
    runs-on: ubuntu-latest
    
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: System libraries
        run: |
          sudo apt-get install -y libpng-dev
          #sudo apt-get install -y librdf0-dev
        
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: |
            any::remotes
            any::blogdown
            any::devtools

      - name: Check installed packages
        run: sh _check_redland.sh
